fix boost build with glibc 2.34 on Linux platforms
Without this patch on Ubuntu 21.10 (impish) with GLIBC 2.34-0ubuntu3
and gcc/g++ 11.2.0 we will get the following error during build boost:

./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "("
   60 | #if PTHREAD_STACK_MIN > 0
      |     ^~~~~~~~~~~~~~~~~

Useful links:

- https://github.com/KomodoPlatform/komodo/pull/532 (original issue)
- https://github.com/boostorg/thread/issues/283

Used commits from boost:

- https://github.com/boostorg/thread/commit/74fb0a26099bc51d717f5f154b37231ce7df3e98 - Revert change to elide a warning that caused Solaris builds to fail.
- https://github.com/boostorg/thread/commit/f9d0e594d43afcb4ab0043117249feb266ba4515 - Fix -Wsign-compare warning with glibc 2.34 on Linux platforms.